name: daily_spend
description: A production-ready expense tracking mobile application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.2
  pluto_grid: ^8.1.0
  excel: ^4.0.6
  intl: ^0.20.2
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  uuid: ^4.3.3
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
